version: '3'

services: 
    mongodb:
        image: mongo:latest
        container_name: mongodb_theos
        hostname: mongodb_theos
        environment:
            GET_HOST_FROM: dns
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: devs
        volumes: 
            - ./backend/database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        ports: 
            - 27017:27017
        networks: 
            - network_theos

    mongo-express:
        image: mongo-express
        container_name: mongo-express_theos
        environment:
            GET_HOST_FROM: dns
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_AUTH_DATABASE: devs
            ME_CONFIG_MONGODB_SERVER: mongodb
        ports:
            - 8081:8081
        networks: 
            - network_theos
        depends_on: 
            - mongodb

networks: 
    network_theos:
        driver: bridge