version: '3'

services: 
    backend-theos:
        image: petersonsalme/backend-theos:v1
        container_name: backend_theos
        hostname: backend_theos
        restart: on-failure
        build: 
            context: .
            dockerfile: docker/backend/Dockerfile
        environment: 
            GET_HOST_FROM: dns
            MONGODB_URI: mongodb://peterson:peterson@mongodb:27017/devs
        ports: 
            - 8000:8000
        depends_on: 
            - mongodb
        links:
            - mongodb
        networks: 
            - network_theos

    mongodb:
        image: mongo:latest
        container_name: mongodb_theos
        hostname: mongodb_theos
        environment:
            GET_HOST_FROM: dns
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: devs
        volumes: 
            - ./backend/src/database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        ports: 
            - 27017:27017
        networks: 
            - network_theos

    mongo-express:
        image: mongo-express
        container_name: mongo-express_theos
        environment:
            GET_HOST_FROM: dns
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_AUTH_DATABASE: devs
            ME_CONFIG_MONGODB_SERVER: mongodb
        ports:
            - 8081:8081
        networks: 
            - network_theos
        depends_on: 
            - mongodb

networks: 
    network_theos:
        driver: bridge